//! Deterministic map derivation. The geometric maps are **computed**, not generated, so
//! they're pixel-aligned to the albedo by construction — no VAE drift, no network, instant.
//! This is also where the "adjust" sliders become real: `detail_routing`,
//! `flip_y`, `radius`, `bit_depth_16`, `strength`, `invert` are the parameters of these passes.
//!
//! The classic chain (Materialize/Laigter): **height → normal** (Sobel), **height → AO**
//! (cavity/horizon), **albedo → opacity** (mask), and **albedo → height** (luminance shaped by
//! the macro↔micro `detail_routing` split) when height isn't AI-generated.

use crate::data::MapId;

/// Which maps are derived (computed) vs. AI-generated (semantic), by default. The per-map
/// AI⇄derived toggle in the UI can promote any map to a full AI generation.
pub const fn default_path(id: MapId) -> DerivePath {
    match id {
        MapId::Albedo | MapId::Roughness | MapId::Metallic | MapId::Emission => DerivePath::Ai,
        MapId::Normal | MapId::Ao | MapId::Transparency | MapId::Displacement => DerivePath::Derived,
    }
}

/// Whether a map is AI-generated or computed.
#[derive(Clone, Copy, Debug, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub enum DerivePath {
    /// Generated by a provider (semantic judgment).
    Ai,
    /// Computed deterministically (aligned by construction).
    Derived,
}

/// Parameters for a derivation pass. Mirrors the per-map `MapState` adjust fields.
#[derive(Clone, Copy, Debug)]
pub struct DeriveParams {
    /// Non-destructive strength multiplier on the result (1.0 = as computed).
    pub strength: f32,
    /// Invert the result (e.g. height direction, roughness polarity).
    pub invert: bool,
    /// Flip the normal map's green channel (OpenGL Y+ ⇄ DirectX Y−).
    pub flip_y: bool,
    /// AO sampling radius, 0..1 (fraction of image size).
    pub radius: f32,
    /// Macro ↔ micro split for height from albedo (0..100; ~10 = displacement owns 10%).
    pub detail_routing: f32,
}

impl Default for DeriveParams {
    fn default() -> Self {
        Self {
            strength: 1.0,
            invert: false,
            flip_y: false,
            radius: 0.35,
            detail_routing: 10.0,
        }
    }
}

// ── Grayscale helpers ──────────────────────────────────────────────────────

fn luminance(r: u8, g: u8, b: u8) -> f32 {
    // Rec. 709 luma.
    0.2126 * (r as f32 / 255.0) + 0.7152 * (g as f32 / 255.0) + 0.0722 * (b as f32 / 255.0)
}

fn to_gray(px: &[u8], size: usize) -> Vec<f32> {
    let mut out = vec![0.0f32; size * size];
    let (pixels, _) = px.as_chunks::<4>();
    for (i, p) in pixels.iter().enumerate() {
        out[i] = luminance(p[0], p[1], p[2]);
    }
    out
}

fn gray_to_rgba(gray: &[f32], size: usize, invert: bool, strength: f32) -> Vec<u8> {
    let mut out = vec![0u8; size * size * 4];
    let (pixels, _) = out.as_chunks_mut::<4>();
    for (i, p) in pixels.iter_mut().enumerate() {
        let mut v = gray[i] * strength;
        if invert {
            v = 1.0 - v;
        }
        let g = (v.clamp(0.0, 1.0) * 255.0).round() as u8;
        *p = [g, g, g, 255];
    }
    out
}

/// Separable box blur over a grayscale field (radius in pixels). Used to split macro/micro.
fn blur_gray(src: &[f32], size: usize, radius: usize) -> Vec<f32> {
    if radius == 0 {
        return src.to_vec();
    }
    let r = radius as i32;
    let mut tmp = vec![0.0f32; size * size];
    let mut out = vec![0.0f32; size * size];
    // horizontal
    for y in 0..size {
        for x in 0..size {
            let mut acc = 0.0;
            let mut cnt = 0.0;
            for k in -r..=r {
                let xx = x as i32 + k;
                if xx >= 0 && xx < size as i32 {
                    acc += src[y * size + xx as usize];
                    cnt += 1.0;
                }
            }
            tmp[y * size + x] = acc / cnt;
        }
    }
    // vertical
    for y in 0..size {
        for x in 0..size {
            let mut acc = 0.0;
            let mut cnt = 0.0;
            for k in -r..=r {
                let yy = y as i32 + k;
                if yy >= 0 && yy < size as i32 {
                    acc += tmp[yy as usize * size + x];
                    cnt += 1.0;
                }
            }
            out[y * size + x] = acc / cnt;
        }
    }
    out
}

// ── Height from albedo ─────────────────────────────────────────────────────

/// Height from albedo: a low-pass (macro) and high-pass (micro) luminance split, blended by
/// `detail_routing` (0..100 = % owned by the macro/displacement term). Returns 0..1 heights.
pub fn height_from_albedo(albedo: &[u8], size: usize, params: &DeriveParams) -> Vec<f32> {
    let lum = to_gray(albedo, size);
    // Macro = heavily blurred; micro = residual (albedo - macro). detail_routing blends them.
    let macro_r = (size as f32 * 0.04).max(2.0) as usize;
    let macro_field = blur_gray(&lum, size, macro_r);
    let macro_frac = (params.detail_routing / 100.0).clamp(0.0, 1.0);
    let micro_frac = 1.0 - macro_frac;
    let mut height = vec![0.0f32; size * size];
    for i in 0..size * size {
        let micro = (lum[i] - macro_field[i]) + 0.5; // center micro at mid
        height[i] = (macro_field[i] * macro_frac + micro * micro_frac).clamp(0.0, 1.0);
    }
    height
}

/// Displacement map (RGBA8) from a height field, honoring invert/strength. 16-bit export is
/// handled separately at export time (`png` / EXR); the in-app map is 8-bit RGBA.
pub fn displacement_from_height(height: &[f32], size: usize, params: &DeriveParams) -> Vec<u8> {
    gray_to_rgba(height, size, params.invert, params.strength)
}

// ── Normal from height (Sobel) ─────────────────────────────────────────────

/// Normal map from height: Sobel gradient → tangent-space normal. Neutral flat ≈ RGB
/// (128,128,255). `flip_y` flips the green channel (OpenGL Y+ ⇄ DirectX Y−). `strength`
/// scales the gradient (higher = more pronounced relief).
pub fn normal_from_height(height: &[f32], size: usize, params: &DeriveParams) -> Vec<u8> {
    let mut out = vec![0u8; size * size * 4];
    let (pixels, _) = out.as_chunks_mut::<4>();
    let s = params.strength * 2.0; // gradient scale
    for y in 0..size {
        for x in 0..size {
            let i = y * size + x;
            let xl = height[y * size + x.saturating_sub(1)];
            let xr = height[y * size + (x + 1).min(size - 1)];
            let yt = height[y.saturating_sub(1) * size + x];
            let yb = height[(y + 1).min(size - 1) * size + x];
            let dx = (xr - xl) * s;
            let mut dy = (yb - yt) * s;
            if params.flip_y {
                dy = -dy;
            }
            // Tangent-space normal (-dx, -dy, 1) normalized. Invert flips the relief polarity
            // (bumps ⇄ dents) by negating the tangent slope.
            let sign = if params.invert { -1.0 } else { 1.0 };
            let (mut nx, mut ny, mut nz) = (-dx * sign, -dy * sign, 1.0f32);
            let len = (nx * nx + ny * ny + nz * nz).sqrt();
            if len > 1e-6 {
                nx /= len;
                ny /= len;
                nz /= len;
            }
            let r = ((nx * 0.5 + 0.5) * 255.0).round() as u8;
            let g = ((ny * 0.5 + 0.5) * 255.0).round() as u8;
            let b = ((nz * 0.5 + 0.5) * 255.0).round() as u8;
            pixels[i] = [r, g, b, 255];
        }
    }
    out
}

// ── AO from height (cavity) ────────────────────────────────────────────────

/// Ambient occlusion from height: a cavity/horizon approximation. For each pixel, sample
/// neighbors within `radius`; the more the surroundings rise above the pixel, the more it's
/// occluded. White = fully exposed, darker = crevice/contact shadow.
pub fn ao_from_height(height: &[f32], size: usize, params: &DeriveParams) -> Vec<u8> {
    let mut out = vec![0.0f32; size * size];
    let max_r = ((size as f32 * params.radius.clamp(0.01, 1.0)) as i32).max(1);
    // Sample a small fixed ring set for speed (8 directions × a few radii).
    const DIRS: [(i32, i32); 8] = [(1, 0), (-1, 0), (0, 1), (0, -1), (1, 1), (1, -1), (-1, 1), (-1, -1)];
    for y in 0..size {
        for x in 0..size {
            let i = y * size + x;
            let h = height[i];
            let mut occ = 0.0f32;
            let mut samples = 0.0f32;
            for step in [max_r / 3, (max_r * 2) / 3, max_r] {
                if step == 0 {
                    continue;
                }
                for (dx, dy) in DIRS {
                    let xx = x as i32 + dx * step;
                    let yy = y as i32 + dy * step;
                    if xx >= 0 && xx < size as i32 && yy >= 0 && yy < size as i32 {
                        let nh = height[yy as usize * size + xx as usize];
                        // Height above this pixel occludes; scale down with distance.
                        occ += (nh - h).max(0.0) / (step as f32 / max_r as f32);
                        samples += 1.0;
                    }
                }
            }
            let occ_avg = if samples > 0.0 { occ / samples } else { 0.0 };
            // Exposed = 1 - occlusion (softened).
            out[i] = (1.0 - (occ_avg * 2.0).min(1.0)).clamp(0.0, 1.0);
        }
    }
    gray_to_rgba(&out, size, params.invert, params.strength)
}

// ── Opacity from albedo ────────────────────────────────────────────────────

/// Opacity/transparency mask from albedo: glass/cut-out regions become transparent. A simple
/// luminance+saturation threshold stands in for segmentation — physically see-through surfaces
/// (dark glass, gaps) go non-white; solid surfaces stay opaque. Honors invert/strength.
pub fn opacity_from_albedo(albedo: &[u8], size: usize, params: &DeriveParams) -> Vec<u8> {
    let (pixels, _) = albedo.as_chunks::<4>();
    let mut mask = vec![0.0f32; size * size];
    for (i, p) in pixels.iter().enumerate() {
        let (r, g, b, a) = (p[0], p[1], p[2], p[3]);
        // Start from the albedo's own alpha (glass was painted transparent by the renderer),
        // then bias very dark regions toward transparent.
        let lum = luminance(r, g, b);
        let alpha_term = a as f32 / 255.0;
        let dark_glass = if lum < 0.18 { 0.6 } else { 1.0 };
        mask[i] = (alpha_term * dark_glass).clamp(0.0, 1.0);
    }
    gray_to_rgba(&mask, size, params.invert, params.strength)
}

/// Roughness from albedo luminance — the classic offline heuristic (brighter, cleaner
/// surface reads smoother; darker grime reads rougher), with contrast compressed around a
/// matte midpoint so the result stays in the plausible band instead of swinging fully
/// glossy/rough. A deterministic stand-in for the AI path, not a physical claim.
pub fn roughness_from_albedo(albedo: &[u8], size: usize, params: &DeriveParams) -> Vec<u8> {
    let (pixels, _) = albedo.as_chunks::<4>();
    let mut mask = vec![0.0f32; size * size];
    for (i, p) in pixels.iter().enumerate() {
        let lum = luminance(p[0], p[1], p[2]);
        mask[i] = (0.62 + (0.5 - lum) * 0.55).clamp(0.0, 1.0);
    }
    gray_to_rgba(&mask, size, params.invert, params.strength)
}

/// Metallic from albedo chroma, near-binary: low-saturation pixels in the mid-brightness
/// band read as bare conductor; anything colored, very dark, or blown-out reads dielectric.
pub fn metallic_from_albedo(albedo: &[u8], size: usize, params: &DeriveParams) -> Vec<u8> {
    let smoothstep = |e0: f32, e1: f32, x: f32| {
        let t = ((x - e0) / (e1 - e0)).clamp(0.0, 1.0);
        t * t * (3.0 - 2.0 * t)
    };
    let (pixels, _) = albedo.as_chunks::<4>();
    let mut mask = vec![0.0f32; size * size];
    for (i, p) in pixels.iter().enumerate() {
        let (r, g, b) = (p[0] as f32 / 255.0, p[1] as f32 / 255.0, p[2] as f32 / 255.0);
        let max = r.max(g).max(b);
        let sat = if max > 0.0 { (max - r.min(g).min(b)) / max } else { 0.0 };
        let grayness = 1.0 - smoothstep(0.10, 0.28, sat);
        let band = smoothstep(0.16, 0.30, max) * (1.0 - smoothstep(0.85, 0.97, max));
        // Push toward 0/1 — metallic maps want near-binary values.
        mask[i] = smoothstep(0.35, 0.75, grayness * band);
    }
    gray_to_rgba(&mask, size, params.invert, params.strength)
}

// ── Dispatch ───────────────────────────────────────────────────────────────

/// Derive a map from the current albedo. `height` feeds Displacement/Normal/Ao (computed
/// from the albedo when absent) and is ignored otherwise. Returns the RGBA8 map at
/// `size × size`.
#[tracing::instrument(skip(albedo, height, params), fields(?id, size))]
pub fn derive_map(id: MapId, albedo: &[u8], height: Option<&[f32]>, size: usize, params: &DeriveParams) -> Vec<u8> {
    let with_height = |f: fn(&[f32], usize, &DeriveParams) -> Vec<u8>| match height {
        Some(h) => f(h, size, params),
        None => f(&height_from_albedo(albedo, size, params), size, params),
    };
    match id {
        MapId::Displacement => with_height(displacement_from_height),
        MapId::Normal => with_height(normal_from_height),
        MapId::Ao => with_height(ao_from_height),
        MapId::Transparency => opacity_from_albedo(albedo, size, params),
        MapId::Roughness => roughness_from_albedo(albedo, size, params),
        MapId::Metallic => metallic_from_albedo(albedo, size, params),
        // A derived emission map is unlit by definition — emission needs semantic judgment.
        MapId::Emission => {
            let mut px = vec![0u8; size * size * 4];
            for p in px.as_chunks_mut::<4>().0 {
                p[3] = 255;
            }
            px
        }
        MapId::Albedo => albedo.to_vec(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn flat_albedo(size: usize, v: u8) -> Vec<u8> {
        let mut px = vec![0u8; size * size * 4];
        for p in px.as_chunks_mut::<4>().0 {
            *p = [v, v, v, 255];
        }
        px
    }

    #[test]
    fn flat_height_yields_neutral_normal() {
        let size = 8;
        let height = vec![0.5f32; size * size];
        let n = normal_from_height(&height, size, &DeriveParams::default());
        // A flat field has zero gradient → normal (0,0,1) → RGB ≈ (128,128,255).
        for p in n.as_chunks::<4>().0 {
            assert!((p[0] as i16 - 128).abs() <= 2, "r={}", p[0]);
            assert!((p[1] as i16 - 128).abs() <= 2, "g={}", p[1]);
            assert_eq!(p[2], 255);
        }
    }

    #[test]
    fn flip_y_inverts_green_channel() {
        let size = 8;
        // Asymmetric ramp (x weighted more than y) so dx ≠ dy and the green mirror is visible.
        let mut height = vec![0.0f32; size * size];
        for y in 0..size {
            for x in 0..size {
                height[y * size + x] = (x as f32 * 3.0 + y as f32) / (size as f32 * 4.0);
            }
        }
        let base = normal_from_height(&height, size, &DeriveParams::default());
        let flipped = normal_from_height(
            &height,
            size,
            &DeriveParams {
                flip_y: true,
                ..Default::default()
            },
        );
        let i = 3 * size + 3;
        assert_eq!(base[i * 4 + 2], flipped[i * 4 + 2], "blue (z) unchanged");
        // Green channel (y gradient) mirrored around 128; red (x gradient) unchanged.
        let r0 = base[i * 4] as i16 - 128;
        let r1 = flipped[i * 4] as i16 - 128;
        assert_eq!(r0, r1, "red unchanged");
        let g0 = base[i * 4 + 1] as i16 - 128;
        let g1 = flipped[i * 4 + 1] as i16 - 128;
        assert!((g0 + g1).abs() <= 1, "green mirrored within rounding ({} vs {})", g0, g1);
        assert_ne!(g0, 0, "gradient nonzero so the mirror is observable");
    }

    /// The semantic heuristics produce real maps, not albedo copies: brighter albedo reads
    /// smoother, darker rougher; derived emission is unlit.
    #[test]
    fn semantic_heuristics_are_not_albedo_copies() {
        let size = 8;
        let params = DeriveParams::default();
        let bright = flat_albedo(size, 200);
        let dark = flat_albedo(size, 30);
        let rough_bright = roughness_from_albedo(&bright, size, &params);
        let rough_dark = roughness_from_albedo(&dark, size, &params);
        assert!(rough_bright[0] < 128, "bright surface reads smooth, got {}", rough_bright[0]);
        assert!(rough_dark[0] > rough_bright[0], "darker albedo reads rougher");
        let emission = derive_map(MapId::Emission, &bright, None, size, &params);
        for p in emission.as_chunks::<4>().0 {
            assert_eq!(&p[..3], &[0, 0, 0], "derived emission is unlit");
            assert_eq!(p[3], 255);
        }
    }

    /// Metallic is near-binary: neutral gray reads as bare conductor, saturated paint as
    /// dielectric.
    #[test]
    fn metallic_heuristic_is_near_binary() {
        let size = 8;
        let params = DeriveParams::default();
        let gray = flat_albedo(size, 128);
        let metal = metallic_from_albedo(&gray, size, &params);
        assert!(metal[0] > 200, "neutral gray reads metallic, got {}", metal[0]);
        let mut painted = vec![0u8; size * size * 4];
        for p in painted.as_chunks_mut::<4>().0 {
            *p = [200, 60, 40, 255];
        }
        let dielectric = metallic_from_albedo(&painted, size, &params);
        assert!(dielectric[0] < 40, "saturated paint reads dielectric, got {}", dielectric[0]);
    }

    #[test]
    fn flat_albedo_yields_mid_height_and_full_ao() {
        let size = 16;
        let albedo = flat_albedo(size, 128);
        let params = DeriveParams::default();
        let h = height_from_albedo(&albedo, size, &params);
        // Flat luminance → macro == lum, micro residual ≈ 0 → height ≈ lum.
        for v in &h {
            assert!((v - 128.0 / 255.0).abs() < 0.05, "h={v}");
        }
        let ao = ao_from_height(&h, size, &params);
        // Uniform height → no occlusion → white.
        for p in ao.as_chunks::<4>().0 {
            assert!(p[0] >= 250, "ao r={}", p[0]);
        }
    }
}
